FROM debian
ENV locale "en_AU"  #from configuration if set
ENV charset" "UTF-8" #from configuration if set

ADD packing/scripts/ /tmp/packing/scripts/
ADD packing/early/ /

#Order here is important 
RUN  /tmp/packing/scripts/early/repos &&\
    /tmp/packing/scripts/early/apt &&\
    /tmp/packing/scripts/early/locale &&\
    /tmp/packing/scripts/early/set_time_zone 

    

RUN /tmp/packing/scripts/late/add apt-transport-https unzip

RUN /tmp/packing/scripts/late/remove bootlogd dmidecode eudev gdbm-l10n iptables kmod krb5-locales libip4tc0 libip6tc0 libiptc0 libkmod2 libnetfilter-conntrack3 libnfnetlink0 libnftnl11 tasksel tasksel-data 

RUN /tmp/packing/scripts/last/cleanup

#NOTE The three RUN lines should be detect as a continous line of run statements and there be concatentated to a single RUN statement with &&\\n as the seperator 




