#!/bin/sh -e

/tmp/pack/scripts/post-provision-overlay 

#called after install to create configuration files
#example configure db settings file
if test -f /tmp/pack/scripts/user/postsetup.sh
	 then
	 	/tmp/pack/scripts/user/postsetup.sh
fi	 	
	 	
#actions to run after configuration
#migrate database, configure settings stored
# this also where custom installation tasks are to be run
 
if test -f /tmp/pack/scripts/user/post-provision
	 then
	 	  /tmp/pack/scripts/user/post-provision
fi
